### ISSUE TITLE
network architecture

### ISSUE THREAD

**Issue by Light--** [wchliao/multi-task-cifar-10#1]
thanks for sharing. 👍 
You have used a 5 conv layer net in Model(), may i ask where does this architecture design comes from?
It is similar to alexnet, but different in kernel design...
If that is totally your design, why didn't you use other popular networks, like vgg etc.,  Can you share the consideration? And how do you know whether this architecture is effective enough or not?
Thank you and look forward to your reply. 😄 

```python
def Model(num_classes, num_channels):
    layers = [
        nn.Conv2d(num_channels, 32, kernel_size=3, padding=1),
        nn.BatchNorm2d(32),
        nn.ReLU(),
        nn.Conv2d(32, 64, kernel_size=3, padding=1, stride=2),
        nn.BatchNorm2d(64),
        nn.ReLU(),
        nn.Conv2d(64, 64, kernel_size=3, padding=1),
        nn.BatchNorm2d(64),
        nn.ReLU(),
        nn.Conv2d(64, 128, kernel_size=3, padding=1, stride=2),
        nn.BatchNorm2d(128),
        nn.ReLU(),
        nn.Conv2d(128, 128, kernel_size=3, padding=1),
        nn.BatchNorm2d(128),
        nn.ReLU(),
    ]
```

**Comment by wchliao** [comment]
This model is simplified from VGG. 
The purpose of this experiment is to see the difference between the settings. Therefore, it is fine as long as the core models are same. I use this simplified model because the training time is shorter. 
I also did this experiment with more complicated core models such as MobileNetV2. You can check it [here](https://github.com/wchliao/multi-task-mobilenetv2).

**Comment by Light--** [comment]
> You can check it [here](https://github.com/wchliao/multi-task-mobilenetv2).

Thanks very much, i'll check.
